name: Build Linux

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  linux:
    runs-on: ${{ matrix.os }}
    needs: create_release
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake qt5-qmake-bin qtbase5-dev qtbase5-dev-tools
          sudo apt-get install -y libqt5core5a libqt5gui5 libqt5widgets5 libqt5network5 libqt5x11extras5-dev
          sudo apt-get install -y build-essential libopencv-dev libxtst-dev libxrandr-dev libx11-dev

      - name: Build
        run: |
          /usr/bin/x86_64-linux-gnu-qmake
          make -j$(nproc)

      - name: Print Depend
        run: |
          echo "=== apt installed libqt5 packages ==="
          apt list --installed | grep libqt5 || true

          echo "=== depends ==="
          mkdir -p debian
          touch debian/control
          DEPENDS="$(dpkg-shlibdeps -O screenshot 2>/dev/null | awk -F 'Depends=' '{print $2}')"
          echo "DEPENDS=$DEPENDS" >>$GITHUB_ENV
          echo "Depends: $DEPENDS"

      - name: Package deb
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#refs/tags/v}"
          if grep -q '^Version:' package/linux/control; then
            sed -i "/^Version:/c Version: $TAG_VERSION" package/linux/control
          else
            sed -i "/^Package:/a Version: $TAG_VERSION" package/linux/control
          fi
          if grep -q '^Depends:' package/linux/control; then
            sed -i "/^Depends:/c Depends: ${{ env.DEPENDS }}" package/linux/control
          else
            sed -i "/^Maintainer:/a Depends: ${{ env.DEPENDS }}" package/linux/control
          fi

          make package -j
          mv screenshot.deb screenshot-${{ matrix.os }}.deb


      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: screenshot-${{ matrix.os }}.deb
          asset_name: screenshot-${{ matrix.os }}.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload deb
        if: ! startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-${{ github.job }}-${{ matrix.os }}
          path: screenshot-${{ matrix.os }}.deb

