name: Build Linux

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04

      - name: Build
        run: |
          cat "aaaa" >test_file

      - name: Create Release and Upload Release Asset
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            test_file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

